Addition of univariate statistics

diff --git a/MouseKing b/MouseKing
--- a/MouseKing
+++ b/MouseKing
@@ -74,7 +74,9 @@ royale() {
         echo "  -r  Rebuild (default: TRUE)"
         echo ""
         echo "Example:"
-        echo "  MouseKing royale -i Example/data/input.txt -m Example/data/Example_manifest.txt -s MouseKing_Example -o Example/results"
+        echo "  MouseKing royale -i ~/Example/data/input.txt -m ~/Example/data/Example_manifest.txt -s MouseKing_Example -o ~/Example/results"
+        echo ""
+        echo "NOTE: Full paths must be provided"
         return
     fi
 
@@ -258,8 +260,46 @@ processing() {
 
 }
 
-# Function for 'pca' command
-pca() {
+# Function for 'uni' command
+uni() {
+         if [[ -z "$1" || "$1" == "--help" ]]; then
+        echo "Usage: MouseKing uni [options]"
+        echo ""
+        echo "Options:"
+        echo "  -i  Path of the input directory containg the .csv files of processsed LMT data generated by MouseKing process / royale (required)"
+        echo "  -m  File path to the mouse cage manifest (required)"
+        echo "  -s  Save name for the batch of SQlite files to be processed (required)"
+        echo "  -o  Path to the desired output directory (required)"
+        echo ""
+        echo "Example:"
+        echo "  MouseKing processing -i Example/data/input.txt -m Example/data/Example_manifest.txt -s MouseKing_Example -o Example/results"
+        return
+    fi
+
+    while getopts "i:m:s:o:f:d:" opt; do
+        case "$opt" in
+            i) input_dir="$OPTARG" ;;
+            m) manifest="$OPTARG" ;;
+            s) save_name="$OPTARG" ;;
+            o) output="$OPTARG" ;;
+            *) echo "Invalid option"; exit 1 ;;
+        esac
+    done
+
+    effect_reference="${effect_reference:-NULL}"
+
+    if [[ -z "$input_dir" || -z "$manifest" || -z "$save_name" || -z "$output" ]]; then
+        echo "Error: One or more required argument are missing. Please see --help for usage."
+        return 1
+    fi
+
+    echo "Constructing PCA plots for processed LMT data"
+    run_cmd="nextflow run '$globdir/Nextflow/MouseKing_uni.nf' --input_dir '$input_dir' --manifest '$manifest' --save_name '$save_name' --output '$output'"
+    run_command "$run_cmd"
+}
+
+# Function for 'multi' command
+multi() {
          if [[ -z "$1" || "$1" == "--help" ]]; then
         echo "Usage: MouseKing pca [options]"
         echo ""
@@ -341,7 +381,8 @@ The available commands are:
     rebuild                 Rebuilds all detected mouse events in the provided LMT SQlite files
     extract                 Extracts the EVENT and ANIMAL tables from the provided LMT SQlite files
     processing              Performs processing and filtering of the extracted LMT data contained within the EVENT and ANIMAL tables
-    pca                     Constructs PCA plots and performs multivariate statistics for the provided processed LMT data
+    uni                     Performs univariate statistics for the provided processed LMT data
+    multi                   Performs multivariate statistics for the provided processed LMT data
     install                 Installs the environment required to run MouseKing
 EOF
 }
